version: "3.8"

services:
  localstack:
    image: localstack/localstack:3.6
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3,sqs,events
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  localstack_data:
